config/routes.rb
Rails.application.routes.draw do
  root "todo_lists#index"
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        put :done
      end
    end
  end
  resources :invites, only: :create
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invite.rb
# == Schema Information
#
# Table name: invites
#
#  id             :integer          not null, primary key
#  token          :string
#  email          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  my_audience_id :integer          not null
#
class Invite < ApplicationRecord
  before_create :generate_invite_token

  belongs_to :my_audience

  def generate_invite_token
    self.token = SecureRandom.urlsafe_base64(8, false)
  end
end

app/models/membership.rb
# == Schema Information
#
# Table name: memberships
#
#  id             :integer          not null, primary key
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  my_audience_id :integer          not null
#  user_id        :integer          not null
#
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :my_audience
end

app/models/my_audience.rb
# == Schema Information
#
# Table name: my_audiences
#
#  id         :integer          not null, primary key
#  user_email :string
#  todo_list  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class MyAudience < ApplicationRecord
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :invites, dependent: :destroy
end

app/models/todo_item.rb
# == Schema Information
#
# Table name: todo_items
#
#  id           :integer          not null, primary key
#  title        :string
#  todo_list_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  done_at      :datetime
#
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def done?
    done_at.present?
  end
end

app/models/todo_list.rb
# == Schema Information
#
# Table name: todo_lists
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer          not null
#
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy
  belongs_to :user

  def percent_done
    done_todo_items = todo_items.pluck(:done_at).compact.size
    total_todo_items = todo_items.size
    return 0 if total_todo_items == 0

    (100 * done_todo_items.to_f / total_todo_items).round(1)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  sign_in_count          :integer
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :trackable

  has_many :todo_lists, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :my_audiences, through: :memberships, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController

  def create
    @invite = Invite.new(invite_params)
    if @invite.save
       @invite.invite_token
    else
       redirect_to root_path, notice: "Something went wrong!"
    end
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def done
    unless @todo_item.done_at
      @todo_item.update_attribute(:done_at, Time.now)
      redirect_to @todo_list, notice: "Todo item done!"
    else
      @todo_item.update_attribute(:done_at, nil)
      redirect_to @todo_list, notice: "Todo item  NOT done!"
    end
  end

  private

    def set_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def todo_item_params
      params[:todo_item].permit(:title)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_todo_list, only: %i[ show edit update destroy ]

  def index
    @todo_lists = TodoList.paginate(page: params[:page], per_page: 5).order(created_at: :desc)
    case
    when params[:sort] == 'time'
      @todo_lists
    when params[:sort] == 'percentage'
      @todo_lists = TodoList.all.sort_by{ |todo_list| todo_list.percent_done }.reverse.paginate(page: params[:page], per_page: 5)
    end
  end

  def show
  end

  def new
    @todo_list = TodoList.new
  end

  def edit
  end

  def create
    @todo_list = TodoList.new(todo_list_params)
      if @todo_list.save
        redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created" 
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
    if @todo_list.update(todo_list_params)
      redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated" 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  def destroy
    @todo_list.destroy
    redirect_to todo_lists_url, notice: "Todo list was successfully destroyed"
  end

  private

    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    def todo_list_params
      params.require(:todo_list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/invites/_form.html.haml
= form_with(model: @invite, local: true) do |f|
  = f.label :email
  = f.email_field :email
  = f.submit 'Generate invite link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TODOApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/todo_items/_form.html.haml
= form_for([@todo_list, @todo_list.todo_items.build]) do |f| 
 = f.text_field :title, placeholder: "New Todo" 
 = f.submit

app/views/todo_items/_todo_item.html.haml
- if todo_item.done?
  %p{style: "opacity: 0.7;"}
    %strike= todo_item.title
  = link_to "Done", done_todo_list_todo_item_path(@todo_list, todo_item.id), method: :put
- else
  %p= todo_item.title
  = link_to "Done", done_todo_list_todo_item_path(@todo_list, todo_item.id), method: :put

app/views/todo_lists/_form.html.haml
= form_for @todo_list do |f|
  - if @todo_list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@todo.errors.count, "error")} prohibited this todo from being saved:"
      %ul
        - @todo_list.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/todo_lists/edit.html.haml
%h1 Editing todo_list
= render 'form'
= link_to 'Show', @todo_list
= link_to 'Back', todo_lists_path

app/views/todo_lists/index.html.haml
%h1 Todo list
%table
  %thead
    %tr
      %th Title
      %th= link_to "Sorted by created time", sort: "time"
      %th= link_to "Sorted as a percentage", sort: "percentage"
  %tbody
    - @todo_lists.each do |todo_list|
      %tr
        %td= todo_list.title 
        %td= todo_list.created_at.strftime("Created %d.%m.%Y at %H:%M")
        %td= todo_list.todo_items.size
        %td= "#{todo_list.percent_done}%"
        %td= link_to 'Show', todo_list
        %td= link_to 'Edit', edit_todo_list_path(todo_list)
        %td= link_to 'Delete', todo_list, method: :delete, data: { confirm: 'Are you sure?' }
%br
= link_to 'New Todo list', new_todo_list_path
= will_paginate @todo_lists

app/views/todo_lists/new.html.haml
%h1 New todo
= render 'form'
= link_to 'Back', todo_lists_path

app/views/todo_lists/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @todo_list.title
  = @todo_list.created_at.strftime("Created %d.%m.%Y at %H:%M")
#todo_items_wrapper
  = render @todo_list.todo_items
  #form
    = render "todo_items/form"
= link_to 'Edit', edit_todo_list_path(@todo_list)
= link_to 'Back', todo_lists_path
%p
  = render "invites/form"

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post
    %br/